
- name: Clone Spacemacs repo
  vars:
    url: "{{ user.spacemacs_mirror | default(spacemacs_url) }}"
    version: "{{ user.spacemacs_version | default(spacemacs_version) }}"
    username: "{{ user.username }}"
  git:
    repo: "{{ url }}"
    dest: "~{{ username }}/.emacs.d"
    version: "{{ version }}"
  become: yes
  become_user: "{{ username }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: user
    label: "clone {{ url }}@{{ version }}"

- name: Clone Spacemacs user config
  vars:
    url: "{{ user.spacemacs_config_url }}"
    version: "{{ user.spacemacs_config_version | default('HEAD') }}"
    username: "{{ user.username }}"
  git:
    repo: "{{ url }}"
    dest: "~{{ username }}/.spacemacs.d"
    version: "{{ version }}"
  become: yes
  become_user: "{{ username }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: user
    label: "clone {{ url }}@{{ version }}"
  when: user.spacemacs_config_url

- name: Get the Source Code Pro font
  unarchive:
    src: "{{ source_code_pro_url }}"
    dest: /usr/local/src/
    list_files: yes
    remote_src: yes
  register: sourcecodepro_unarchive

- name: Copy Source Code Pro to /usr/share/fonts
  copy:
    src: "{{ sourcecodepro_unarchive.dest }}{{ sourcecodepro_unarchive.files[0] }}OTF/"
    dest: /usr/share/fonts/source-code-pro
    remote_src: yes
  when: sourcecodepro_unarchive.changed
  register: sourcecodepro_copy

- name: Update fc-cache for new font
  command: fc-cache -fv
  when: sourcecodepro_copy.changed
